---
- name: Get the external IP 
  uri:
    url: http://ip.jitonline.net/ip
    return_content: yes
  connection: local
  register: external_ip
  ignore_errors: true
  run_once: true
  tags:
    - always

- name: Set external IP to variable
  set_fact: 
    auth_ip: "{{ external_ip.json.ip }}"
  ignore_errors: true
  when: 
    - external_ip.json.ip
  tags:
    - always
