---
collections:
  - name: ansible.utils
  - name: community.general
  - name: community.docker
  - name: fortinet.fortios
  - name: netbox.netbox
    version: '3.21.0'
  - name: smallstep.cli
  - name: trfore.smallstep

