#    chkmk_pkg_name: check-mk-agent
#    chkmk_pkg_host: http://netmon
#    chkmk_pkg_site: cmk
#    chkmk_pkg_ver: 2.1.0p21

- name: Check to see if check_mk_agent is installed
  command: "dpkg-query -W {{ chkmk_pkg_name }}"
  register: chkmk_pkg_check_deb
  failed_when: chkmk_pkg_check_deb.rc > 1
  changed_when: chkmk_pkg_check_deb.rc == 1

- name: Download check_mk_package
  get_url:
    url="{{ chkmk_pkg_host }}/{{ chkmk_pkg_site }}/check_mk/agents/{{ chkmk_pkg_name }}_{{ chkmk_pkg_ver }}-1_all.deb"
    dest="/tmp/{{ chkmk_pkg_name }}_{{ chkmk_pkg_ver }}.deb"
  when: chkmk_pkg_check_deb.rc == 1 or chkmk_pkg_ver not in chkmk_pkg_check_deb.stdout

- name: Install latest check_mk_agent
  apt: deb="/tmp/{{ chkmk_pkg_name }}_{{ chkmk_pkg_ver }}.deb"
  become: true
  when: chkmk_pkg_check_deb.rc == 1 or chkmk_pkg_ver not in chkmk_pkg_check_deb.stdout
