---

- hosts: envoy
  gather_facts: False
  pre_tasks:
    - name: Install python3, sudo and shadow on Alpine
      raw: |
        if [ -x "$(command -v apk)" ]; then
          if ! [ -x "$(command -v python3)" ] || ! [ -x "$(command -v sudo)" ] || ! [ -x "$(command -v useradd)" ]; then
            apk update && apk add python3 sudo shadow
          fi
        fi
      changed_when: false

    - name: Gather facts
      setup:

  vars_files:
    - ~/ansible_data/vars/envoy.yml
  roles:
    - role: linux_envoy
