---
- name: Show host metadata
  hosts: all
  gather_facts: false
  tasks:
    - name: Display host groups and tags
      debug:
        msg:
          - "Groups: {{ group_names }}"
          - "Tags: {{ tags | default([]) }}"
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
    
