---

- hosts: docker
  gather_facts: False
  pre_tasks:
    - name: Ensure the ansible-venv exists and is used
      ansible.builtin.include_tasks: tasks/ensure_ansible_venv.yml

    - name: Gather facts
      setup:

  vars_files:
    - ~/ansible_data/vars/docker.yml

  roles:
    - role: linux_docker
