---

- hosts: all:!fortigate:!localhost:!semaphore
  collections:
    - trfore.smallstep
  gather_facts: False
  pre_tasks:
    - name: Ensure the ansible-venv exists and is used
      ansible.builtin.include_tasks: tasks/ensure_ansible_venv.yml
      tags:
       - always

    - name: Gather facts
      setup:
      tags:
       - always

  roles:
    - role: linux_baseline
      tags:
       - always
    - role: linux_update
      tags:
       - always
    - role: linux_netbird
      when: 
        - "'skip_netbird' not in (tags | default([]))"
      tags:
       - always
    - role: linux_system
      tags:
       - always
    - role: linux_zabbix
      when: 
        - "'skip_zabbix' not in (tags | default([]))"
      tags:
       - always
    - role: linux_proxmox_client
      when: 
        - "'skip_backup' not in (tags | default([]))"
      tags:
       - always
    - role: linux_docker
      when: 
        - "'docker' in (tags | default([]))"
      tags:
       - always
