---
- name: Update all Linux servers
  hosts: all:!fortigate:!localhost
  gather_facts: no
  pre_tasks:
    - name: Ensure the ansible-venv exists and is used
      ansible.builtin.include_tasks: tasks/ensure_ansible_venv.yml

    - name: Gather facts
      setup:
  roles:
    - role: linux_update
