---

- hosts: all:!fortigate:!localhost:!semaphore
  collections:
    - trfore.smallstep
  gather_facts: False
  pre_tasks:
    - name: Ensure the ansible-venv exists and is used
      ansible.builtin.include_tasks: tasks/ensure_ansible_venv.yml

    - name: Gather facts
      setup:

  roles:
    - role: linux_baseline
    - role: linux_update
    - role: linux_netbird
      when: 
        - "'skip_netbird' not in (host_tags | default([]))"
    - role: linux_system
    - role: linux_snmp
    - role: linux_zabbix
      when: 
        - "'skip_zabbix' not in (host_tags | default([]))"
    - role: linux_proxmox_client
      when: 
        - "'skip_backup' not in (host_tags | default([]))"
    - role: linux_docker
      when: 
        - "'docker_host' in (host_tags | default([]))"
