---

- hosts: debian,ubuntu
  collections:
    - artis3n.tailscale
    - trfore.smallstep
  gather_facts: True
  roles:
    - role: linux_baseline
    - role: linux_update
    - role: linux_netbird
      when: ansible_hostname != 'netbird' 
    - role: linux_system
    - role: linux_snmp
    - role: linux_zabbix
      when: ansible_hostname != 'zabbix' 
    - role: linux_proxmox_client
      when: ansible_hostname != 'backup' 
