---

- hosts: debian,ubuntu
  collections:
    - artis3n.tailscale
    - trfore.smallstep
  gather_facts: True
  roles:
    - role: linux_baseline
    - role: linux_update
    - role: linux_system
    - role: linux_netbird
    - role: linux_snmp
    - role: linux_zabbix
    - role: linux_proxmox
