---

- hosts: routeros
  gather_facts: false

  vars_files:
    - ~/ansible_data/credentials.yml
    - ~/ansible_data/vars/internal.yml
    - ~/ansible_data/vars/routeros.yml

  roles:
    - role: routeros
