---
- name: Install python pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install docker python package
  ansible.builtin.pip:
    name: docker==6.1.3

- name: Install docker-compose python package
  ansible.builtin.pip:
    name: docker-compose

- name: Tear down existing services
  community.docker.docker_compose:
    project_src: /srv
    state: absent

- name: Create and start services
  community.docker.docker_compose:
    project_src: /srv
    pull: true
    removie_orphans: true
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
