---
- name: Set uptime robot tags
  set_fact:
    uptime_robot_tags:
    - "Uptime Robot"
    - FQDN
    - External

- name: Create uptime robot tag
  panos_tag_object:
    provider: '{{ palo_provider }}'
    name: "{{ item }}" 
    color: 'red'
    comments:  "{{ item }}"
    commit: no
  loop: "{{ uptime_robot_tags }}"

- name: Create uptime robot objects
  panos_address_object:
    provider: '{{ palo_provider }}'
    name: 'fqdn-{{ item | trim }}'
    address_type: 'fqdn'
    value: '{{ item | trim }}'
    description: 'Uptime Robot host {{ item | trim }}'
    tag: "{{ uptime_robot_tags }}"
    commit: no
  loop: "{{ uptime_hostname_list }}"
  when: 
    - item != ""
    - item != "\r" 

- name: Create uptime robot group
  panos_address_group:
    provider: '{{ palo_provider }}'
    name: 'Group_Uptime_Robot'
    dynamic_value: "'Uptime Robot'"
    tag: "{{ uptime_robot_tags }}"
    commit: no

