---
- name: enable envoy
  systemd: 
    name: envoy 
    enabled: yes
  become: "{{ become_user | default(true) }}"

- name: restart envoy
  systemd: 
    name: envoy 
    state: restarted
  become: "{{ become_user | default(true) }}"
