---

- name: Update provide to include IP
  set_fact:
    palo_provider:
      ip_address: "{{ ip_address }}"
      api_key: "{{ palo_api_key }}"

- name: Commit all changes
  panos_commit:
    provider: '{{ palo_provider }}'


