- name: Update provide to include IP
  set_fact:
    panos_provider:
      ip_address: "{{ ip_address }}"
      api_key: "{{ palo_api_key }}"

- name: Debug provider
  debug:
    var: panos_provider
    verbosity: 2

- name: Include task to set services
  include_tasks: task_set_services.yml 

- name: Include task to set virtual wires
  include_tasks: task_set_virtual_wire.yml 
  when:
    - virtual_wires | length > 0

- name: Include task to set zones
  include_tasks: task_set_zones.yml 
  when:
    - zones | length > 0

