---

- name: Create static DHCP reservations
  template:
    src: dhcp_static.j2
    dest: /tmp/dhcp_static.conf
  delegate_to: 127.0.0.1

- name: Push static DHCP configuration to router.
  edgeos_config:
    backup: no
    src: /tmp/dhcp_static.conf

- name: Delete config file.
  file:
    path: /tmp/dhcp_static.conf
    state: absent
  delegate_to: 127.0.0.1
