---

#- name: Configure System
#  include_tasks: config.yml

- name: Configure DHCP static reservations
  include_tasks: dhcp_static.yml

  #- name: Install broadcast relay
  #include_tasks: relay.yml
