---

- name: Remove old envoy dir
  file: 
    state: absent
    dest: /var/tmp/envoy
  delegate_to: 127.0.0.1
  run_once: true
  tags:
    - always

- name: Get envoy source
  git: 
    repo: https://github.com/envoyproxy/envoy.git
    dest: /var/tmp/envoy
    depth: 1
  delegate_to: 127.0.0.1
  run_once: true
  tags:
    - always

- name: Copy hot restart script 
  copy:
    src: /var/tmp/envoy/restarter/hot-restarter.py 
    dest: /etc/envoy/hot-restarter.py 
    mode: '0755'
    owner: root
    group: root
  become: "{{ become_user | default(true) }}"   
  tags:
    - always
  
- name: Cleanup local host
  file:
    dest: /var/tmp/envoy
    state: absent
  delegate_to: 127.0.0.1
  run_once: true
  tags:
    - always

- name: Create basic envoy config file
  template:
    src: envoy.j2
    dest: /etc/envoy/config.yaml
    mode: '0644'
    owner: root
    group: root
  become: "{{ become_user | default(true) }}"     
  tags:
    - always

- name: Copy envoy control scripts
  copy:
    src: "{{ item }}"
    dest: "/etc/envoy/{{ item }}"
    mode: '0755'
    owner: root
    group: root
  become: "{{ become_user | default(true) }}"
  loop:
    - check_envoy.sh
    - reload_envoy.sh
    - start-envoy.sh
  tags:
    - always
    
- name: Copy envoy systemd scripts
  copy:
    src: "envoy.service"
    dest: "/etc/systemd/system/envoy.service"
    mode: '0644'
    owner: root
    group: root
  become: "{{ become_user | default(true) }}"
  tags:
    - always
  
- name: Enable envoy server
  systemd:
    name: envoy
    enabled: yes
  become: "{{ become_user | default(true) }}"
  tags:
    - always
