---

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family == 'Debian'

- name: Add required packages for docker (Debian family)
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-pip
    state: latest
    update_cache: yes
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family == 'Debian'

- name: Download Docker GPG key (Ubuntu)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: "{{ become_user | default(true) }}"
  when: ansible_distribution == 'Ubuntu'

- name: Add Ubuntu docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: "{{ become_user | default(true) }}"
  when: ansible_distribution == 'Ubuntu'

- name: Download Docker GPG key (Debian)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: "{{ become_user | default(true) }}"
  when: ansible_distribution == 'Debian'

- name: Add Debian docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  become: "{{ become_user | default(true) }}"
  when: ansible_distribution == 'Debian'

- name: Add docker package (Debian family)
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: latest
    update_cache: yes
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family == 'Debian'

- name: Add docker python package (Debian family)
  ansible.builtin.apt:
    name: 
      - python3-docker
      - python3-docker-compose
    state: latest
    update_cache: yes
  become: "{{ become_user | default(true) }}"
  when: ansible_distribution == 'Debian'

- name: Add docker and py3-pip packages (Alpine)
  community.general.apk:
    name: 
      - docker
      - py3-pip
      - docker-compose
    state: latest
    update_cache: yes
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family == 'Alpine'

- name: Install python modules for managing docker (Alpine)
  ansible.builtin.pip:
    name: 
      - docker
      - docker-compose
    state: latest
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family == 'Alpine'

- name: Install python modules for managing docker (Non-Alpine)
  ansible.builtin.pip:
    name: 
      - docker
      - docker-compose
    state: latest
  become: "{{ become_user | default(true) }}"
  when: ansible_os_family != 'Alpine'

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: "{{ become_user | default(true) }}"
