---

- name: Configure armv71 metricbeat
  include_tasks: task_arm_metricbeat.yml 
  when: ansible_architecture == "armv7l"
  tags:
    - always

- name: Configure x86_64 metricbeat
  include_tasks: task_x86_64_metricbeat.yml 
  when: ansible_architecture == "x86_64"
  tags:
    - always

- name: Install metricbeat
  include_tasks: task_install_metricbeat.yml 
  tags:
    - always

- name: Configure metricbeat
  include_tasks: task_configure_metricbeat.yml 
  tags:
    - always
