---

- name: Add GPG key for x86_64
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present 
  become: "{{ become_user | default(true) }}"
  tags:
    - always

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: "{{ become_user | default(true) }}"
  tags:
    - always

- name: Add metricbeat repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
  become: "{{ become_user | default(true) }}"
  tags:
    - always
