---

- name: Update provide to include IP
  set_fact:
    palo_provider:
      ip_address: "{{ ip_address }}"
      api_key: "{{ palo_api_key }}"

- name: Debug provider
  debug:
    var: palo_provider
    verbosity: 2

- name: Include task to get Cloudflare hostnames
  include_tasks: task_get_cloudflare_hosts.yml 

- name: Include task to update palo group
  include_tasks: task_update_palo_group.yml
